<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Payment Gateway Settings
    |--------------------------------------------------------------------------
    |
    | Each group below appears as a tab in the Payment Gateway Settings page.
    | When a new gateway is added via `php artisan make:payment-gateway`,
    | a new tab group is appended here automatically.
    |
    | Group-level keys:
    |   label        – Tab label
    |   icon         – Phosphor icon class
    |   description  – Shown below the tab title
    |   webhook_url  – If true, shows a copy-to-clipboard webhook URL box
    |   settings     – Field definitions (same format as config/settings.php)
    |
    | Setting-level extra keys:
    |   layout       – 'sidebar' renders in right column; default renders in left
    |
    */

    'stripe' => [
        'label' => 'Stripe',
        'layout' => 'full',
        'icon' => 'ph ph-stripe-logo',
        'description' => 'Stripe payment gateway credentials',
        'webhook_url' => true,
        'settings' => [
            'stripe_enabled' => [
                'type' => 'feature',
                'label' => 'Enable Stripe',
                'hint' => 'Accept payments via Stripe',
                'default' => false,
            ],
            'stripe_publishable_key' => [
                'type' => 'text',
                'label' => 'Publishable Key',
                'hint' => 'Your Stripe publishable key (pk_...)',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'stripe_secret_key' => [
                'type' => 'password',
                'label' => 'Secret Key',
                'hint' => 'Your Stripe secret key (sk_...)',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'stripe_webhook_secret' => [
                'type' => 'password',
                'label' => 'Webhook Secret',
                'hint' => 'Webhook signing secret (whsec_...)',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'stripe_supported_currencies' => [
                'type' => 'tags',
                'label' => 'Supported Currencies',
                'hint' => 'Select currencies this gateway accepts',
                'default' => '',
                'layout' => 'sidebar',
            ],
            'stripe_logo' => [
                'type' => 'media',
                'label' => 'Gateway Logo',
                'hint' => 'Logo displayed at checkout',
                'default' => null,
                'accept' => 'image',
                'layout' => 'sidebar',
            ],
            'stripe_min_amount' => [
                'type' => 'number',
                'label' => 'Minimum Amount',
                'hint' => 'Minimum payment amount (0 = no limit)',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'stripe_max_amount' => [
                'type' => 'number',
                'label' => 'Maximum Amount',
                'hint' => 'Maximum payment amount (0 = no limit)',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'stripe_fixed_charge' => [
                'type' => 'number',
                'label' => 'Fixed Charge',
                'hint' => 'Fixed fee added to each payment',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'stripe_percent_charge' => [
                'type' => 'number',
                'label' => 'Percent Charge',
                'hint' => 'Percentage fee added to each payment',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0|max:100',
                'layout' => 'sidebar',
            ],
        ],
    ],

    'paypal' => [
        'label' => 'PayPal',
        'layout' => 'full',
        'icon' => 'ph ph-paypal-logo',
        'description' => 'PayPal REST API credentials',
        'webhook_url' => true,
        'settings' => [
            'paypal_enabled' => [
                'type' => 'feature',
                'label' => 'Enable PayPal',
                'hint' => 'Accept payments via PayPal',
                'default' => false,
            ],
            'paypal_client_id' => [
                'type' => 'text',
                'label' => 'Client ID',
                'hint' => 'Your PayPal REST API client ID',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'paypal_client_secret' => [
                'type' => 'password',
                'label' => 'Client Secret',
                'hint' => 'Your PayPal REST API client secret',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'paypal_sandbox' => [
                'type' => 'feature',
                'label' => 'Sandbox Mode',
                'hint' => 'Use PayPal sandbox environment for testing',
                'default' => true,
            ],
            'paypal_supported_currencies' => [
                'type' => 'tags',
                'label' => 'Supported Currencies',
                'default' => '',
                'layout' => 'sidebar',
            ],
            'paypal_logo' => [
                'type' => 'media',
                'label' => 'Gateway Logo',
                'default' => null,
                'accept' => 'image',
                'layout' => 'sidebar',
            ],
            'paypal_min_amount' => [
                'type' => 'number',
                'label' => 'Minimum Amount',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'paypal_max_amount' => [
                'type' => 'number',
                'label' => 'Maximum Amount',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'paypal_fixed_charge' => [
                'type' => 'number',
                'label' => 'Fixed Charge',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'paypal_percent_charge' => [
                'type' => 'number',
                'label' => 'Percent Charge',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0|max:100',
                'layout' => 'sidebar',
            ],
        ],
    ],

    'razorpay' => [
        'label' => 'Razorpay',
        'layout' => 'full',
        'icon' => 'ph ph-currency-inr',
        'description' => 'Razorpay payment gateway credentials',
        'webhook_url' => true,
        'settings' => [
            'razorpay_enabled' => [
                'type' => 'feature',
                'label' => 'Enable Razorpay',
                'hint' => 'Accept payments via Razorpay',
                'default' => false,
            ],
            'razorpay_key_id' => [
                'type' => 'text',
                'label' => 'Key ID',
                'hint' => 'Your Razorpay key ID (rzp_...)',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'razorpay_key_secret' => [
                'type' => 'password',
                'label' => 'Key Secret',
                'hint' => 'Your Razorpay key secret',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'razorpay_supported_currencies' => [
                'type' => 'tags',
                'label' => 'Supported Currencies',
                'default' => '',
                'layout' => 'sidebar',
            ],
            'razorpay_logo' => [
                'type' => 'media',
                'label' => 'Gateway Logo',
                'default' => null,
                'accept' => 'image',
                'layout' => 'sidebar',
            ],
            'razorpay_min_amount' => [
                'type' => 'number',
                'label' => 'Minimum Amount',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'razorpay_max_amount' => [
                'type' => 'number',
                'label' => 'Maximum Amount',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'razorpay_fixed_charge' => [
                'type' => 'number',
                'label' => 'Fixed Charge',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'razorpay_percent_charge' => [
                'type' => 'number',
                'label' => 'Percent Charge',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0|max:100',
                'layout' => 'sidebar',
            ],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | SSLCommerz — hidden from the settings UI.
    |--------------------------------------------------------------------------
    | The driver and manager registration remain in place; only this config
    | tab is disabled so the gateway no longer appears in the admin UI or the
    | enabled-gateway list. Uncomment this block to restore it.
    |
    | 'sslcommerz' => [
    |     'label' => 'SSLCommerz',
    |     'layout' => 'full',
    |     'icon' => 'ph ph-bank',
    |     'description' => 'SSLCommerz payment gateway credentials (Bangladesh)',
    |     'webhook_url' => true,
    |     'settings' => [
    |         'sslcommerz_enabled' => ['type' => 'feature', 'label' => 'Enable SSLCommerz', 'hint' => 'Accept payments via SSLCommerz', 'default' => false],
    |         'sslcommerz_store_id' => ['type' => 'text', 'label' => 'Store ID', 'hint' => 'Your SSLCommerz store ID', 'default' => '', 'rules' => 'nullable|string|max:255'],
    |         'sslcommerz_store_password' => ['type' => 'password', 'label' => 'Store Password', 'hint' => 'Your SSLCommerz store password', 'default' => '', 'rules' => 'nullable|string|max:255'],
    |         'sslcommerz_sandbox' => ['type' => 'feature', 'label' => 'Sandbox Mode', 'hint' => 'Use SSLCommerz sandbox environment for testing', 'default' => true],
    |         'sslcommerz_supported_currencies' => ['type' => 'tags', 'label' => 'Supported Currencies', 'default' => '', 'layout' => 'sidebar'],
    |         'sslcommerz_logo' => ['type' => 'media', 'label' => 'Gateway Logo', 'default' => null, 'accept' => 'image', 'layout' => 'sidebar'],
    |         'sslcommerz_min_amount' => ['type' => 'number', 'label' => 'Minimum Amount', 'default' => '0', 'rules' => 'nullable|numeric|min:0', 'layout' => 'sidebar'],
    |         'sslcommerz_max_amount' => ['type' => 'number', 'label' => 'Maximum Amount', 'default' => '0', 'rules' => 'nullable|numeric|min:0', 'layout' => 'sidebar'],
    |         'sslcommerz_fixed_charge' => ['type' => 'number', 'label' => 'Fixed Charge', 'default' => '0', 'rules' => 'nullable|numeric|min:0', 'layout' => 'sidebar'],
    |         'sslcommerz_percent_charge' => ['type' => 'number', 'label' => 'Percent Charge', 'default' => '0', 'rules' => 'nullable|numeric|min:0|max:100', 'layout' => 'sidebar'],
    |     ],
    | ],
    */

    'paystack' => [
        'label' => 'Paystack',
        'layout' => 'full',
        'icon' => 'ph ph-wallet',
        'description' => 'Paystack payment gateway credentials (Africa)',
        'webhook_url' => true,
        'settings' => [
            'paystack_enabled' => [
                'type' => 'feature',
                'label' => 'Enable Paystack',
                'hint' => 'Accept payments via Paystack',
                'default' => false,
            ],
            'paystack_public_key' => [
                'type' => 'text',
                'label' => 'Public Key',
                'hint' => 'Your Paystack public key (pk_...)',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'paystack_secret_key' => [
                'type' => 'password',
                'label' => 'Secret Key',
                'hint' => 'Your Paystack secret key (sk_...)',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'paystack_supported_currencies' => [
                'type' => 'tags',
                'label' => 'Supported Currencies',
                'default' => '',
                'layout' => 'sidebar',
            ],
            'paystack_logo' => [
                'type' => 'media',
                'label' => 'Gateway Logo',
                'default' => null,
                'accept' => 'image',
                'layout' => 'sidebar',
            ],
            'paystack_min_amount' => [
                'type' => 'number',
                'label' => 'Minimum Amount',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'paystack_max_amount' => [
                'type' => 'number',
                'label' => 'Maximum Amount',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'paystack_fixed_charge' => [
                'type' => 'number',
                'label' => 'Fixed Charge',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'paystack_percent_charge' => [
                'type' => 'number',
                'label' => 'Percent Charge',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0|max:100',
                'layout' => 'sidebar',
            ],
        ],
    ],

    'flutterwave' => [
        'label' => 'Flutterwave',
        'layout' => 'full',
        'icon' => 'ph ph-globe',
        'description' => 'Flutterwave payment gateway credentials (Africa)',
        'webhook_url' => true,
        'settings' => [
            'flutterwave_enabled' => [
                'type' => 'feature',
                'label' => 'Enable Flutterwave',
                'hint' => 'Accept payments via Flutterwave',
                'default' => false,
            ],
            'flutterwave_public_key' => [
                'type' => 'text',
                'label' => 'Public Key',
                'hint' => 'Your Flutterwave public key (FLWPUBK-...)',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'flutterwave_secret_key' => [
                'type' => 'password',
                'label' => 'Secret Key',
                'hint' => 'Your Flutterwave secret key (FLWSECK-...)',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'flutterwave_encryption_key' => [
                'type' => 'password',
                'label' => 'Encryption Key',
                'hint' => 'Your Flutterwave encryption key',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'flutterwave_supported_currencies' => [
                'type' => 'tags',
                'label' => 'Supported Currencies',
                'default' => '',
                'layout' => 'sidebar',
            ],
            'flutterwave_logo' => [
                'type' => 'media',
                'label' => 'Gateway Logo',
                'default' => null,
                'accept' => 'image',
                'layout' => 'sidebar',
            ],
            'flutterwave_min_amount' => [
                'type' => 'number',
                'label' => 'Minimum Amount',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'flutterwave_max_amount' => [
                'type' => 'number',
                'label' => 'Maximum Amount',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'flutterwave_fixed_charge' => [
                'type' => 'number',
                'label' => 'Fixed Charge',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'flutterwave_percent_charge' => [
                'type' => 'number',
                'label' => 'Percent Charge',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0|max:100',
                'layout' => 'sidebar',
            ],
        ],
    ],

    'mercadopago' => [
        'label' => 'Mercado Pago',
        'layout' => 'full',
        'icon' => 'ph ph-hand-coins',
        'description' => 'Mercado Pago payment gateway credentials (Latin America)',
        'webhook_url' => true,
        'settings' => [
            'mercadopago_enabled' => [
                'type' => 'feature',
                'label' => 'Enable Mercado Pago',
                'hint' => 'Accept payments via Mercado Pago',
                'default' => false,
            ],
            'mercadopago_public_key' => [
                'type' => 'text',
                'label' => 'Public Key',
                'hint' => 'Your Mercado Pago public key (APP_USR-... or TEST-...)',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'mercadopago_access_token' => [
                'type' => 'password',
                'label' => 'Access Token',
                'hint' => 'Your Mercado Pago access token (APP_USR-... or TEST-...)',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'mercadopago_webhook_secret' => [
                'type' => 'password',
                'label' => 'Webhook Secret',
                'hint' => 'Signing secret used to validate webhook notifications',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'mercadopago_sandbox' => [
                'type' => 'feature',
                'label' => 'Sandbox Mode',
                'hint' => 'Use Mercado Pago test credentials for testing',
                'default' => true,
            ],
            'mercadopago_supported_currencies' => [
                'type' => 'tags',
                'label' => 'Supported Currencies',
                'hint' => 'Select currencies this gateway accepts',
                'default' => '',
                'layout' => 'sidebar',
            ],
            'mercadopago_logo' => [
                'type' => 'media',
                'label' => 'Gateway Logo',
                'hint' => 'Logo displayed at checkout',
                'default' => null,
                'accept' => 'image',
                'layout' => 'sidebar',
            ],
            'mercadopago_min_amount' => [
                'type' => 'number',
                'label' => 'Minimum Amount',
                'hint' => 'Minimum payment amount (0 = no limit)',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'mercadopago_max_amount' => [
                'type' => 'number',
                'label' => 'Maximum Amount',
                'hint' => 'Maximum payment amount (0 = no limit)',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'mercadopago_fixed_charge' => [
                'type' => 'number',
                'label' => 'Fixed Charge',
                'hint' => 'Fixed fee added to each payment',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'mercadopago_percent_charge' => [
                'type' => 'number',
                'label' => 'Percent Charge',
                'hint' => 'Percentage fee added to each payment',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0|max:100',
                'layout' => 'sidebar',
            ],
        ],
    ],

    'izipay' => [
        'label' => 'Izipay',
        'layout' => 'full',
        'icon' => 'ph ph-credit-card',
        'description' => 'Izipay payment gateway credentials (Peru)',
        'webhook_url' => true,
        'settings' => [
            'izipay_enabled' => [
                'type' => 'feature',
                'label' => 'Enable Izipay',
                'hint' => 'Accept payments via Izipay',
                'default' => false,
            ],
            'izipay_shop_id' => [
                'type' => 'text',
                'label' => 'Shop ID',
                'hint' => 'Your Izipay shop / user ID',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'izipay_api_password' => [
                'type' => 'password',
                'label' => 'API Password',
                'hint' => 'Your Izipay REST API password (testpassword_... / prodpassword_...)',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'izipay_public_key' => [
                'type' => 'text',
                'label' => 'Public Key',
                'hint' => 'Client-side public key (used by the embedded form)',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'izipay_hmac_key' => [
                'type' => 'password',
                'label' => 'HMAC-SHA256 Key',
                'hint' => 'Key used to verify the kr-hash signature on returns and webhooks',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'izipay_sandbox' => [
                'type' => 'feature',
                'label' => 'Sandbox Mode',
                'hint' => 'Use Izipay test credentials for testing',
                'default' => true,
            ],
            'izipay_supported_currencies' => [
                'type' => 'tags',
                'label' => 'Supported Currencies',
                'hint' => 'Select currencies this gateway accepts',
                'default' => '',
                'layout' => 'sidebar',
            ],
            'izipay_logo' => [
                'type' => 'media',
                'label' => 'Gateway Logo',
                'hint' => 'Logo displayed at checkout',
                'default' => null,
                'accept' => 'image',
                'layout' => 'sidebar',
            ],
            'izipay_min_amount' => [
                'type' => 'number',
                'label' => 'Minimum Amount',
                'hint' => 'Minimum payment amount (0 = no limit)',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'izipay_max_amount' => [
                'type' => 'number',
                'label' => 'Maximum Amount',
                'hint' => 'Maximum payment amount (0 = no limit)',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'izipay_fixed_charge' => [
                'type' => 'number',
                'label' => 'Fixed Charge',
                'hint' => 'Fixed fee added to each payment',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'izipay_percent_charge' => [
                'type' => 'number',
                'label' => 'Percent Charge',
                'hint' => 'Percentage fee added to each payment',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0|max:100',
                'layout' => 'sidebar',
            ],
        ],
    ],

    'mollie' => [
        'label' => 'Mollie',
        'layout' => 'full',
        'icon' => 'ph ph-currency-eur',
        'description' => 'Mollie payment gateway credentials (Europe)',
        'webhook_url' => true,
        'settings' => [
            'mollie_enabled' => [
                'type' => 'feature',
                'label' => 'Enable Mollie',
                'hint' => 'Accept payments via Mollie',
                'default' => false,
            ],
            'mollie_api_key' => [
                'type' => 'password',
                'label' => 'API Key',
                'hint' => 'Your Mollie API key (test_... for testing, live_... for production)',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'mollie_supported_currencies' => [
                'type' => 'tags',
                'label' => 'Supported Currencies',
                'hint' => 'Select currencies this gateway accepts',
                'default' => '',
                'layout' => 'sidebar',
            ],
            'mollie_logo' => [
                'type' => 'media',
                'label' => 'Gateway Logo',
                'hint' => 'Logo displayed at checkout',
                'default' => null,
                'accept' => 'image',
                'layout' => 'sidebar',
            ],
            'mollie_min_amount' => [
                'type' => 'number',
                'label' => 'Minimum Amount',
                'hint' => 'Minimum payment amount (0 = no limit)',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'mollie_max_amount' => [
                'type' => 'number',
                'label' => 'Maximum Amount',
                'hint' => 'Maximum payment amount (0 = no limit)',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'mollie_fixed_charge' => [
                'type' => 'number',
                'label' => 'Fixed Charge',
                'hint' => 'Fixed fee added to each payment',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'mollie_percent_charge' => [
                'type' => 'number',
                'label' => 'Percent Charge',
                'hint' => 'Percentage fee added to each payment',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0|max:100',
                'layout' => 'sidebar',
            ],
        ],
    ],

    'xendit' => [
        'label' => 'Xendit',
        'layout' => 'full',
        'icon' => 'ph ph-qr-code',
        'description' => 'Xendit payment gateway credentials (Southeast Asia)',
        'webhook_url' => true,
        'settings' => [
            'xendit_enabled' => [
                'type' => 'feature',
                'label' => 'Enable Xendit',
                'hint' => 'Accept payments via Xendit',
                'default' => false,
            ],
            'xendit_secret_key' => [
                'type' => 'password',
                'label' => 'Secret Key',
                'hint' => 'Your Xendit secret API key (xnd_...)',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'xendit_webhook_token' => [
                'type' => 'password',
                'label' => 'Webhook Verification Token',
                'hint' => 'Callback token used to validate incoming webhooks (x-callback-token)',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'xendit_supported_currencies' => [
                'type' => 'tags',
                'label' => 'Supported Currencies',
                'hint' => 'Select currencies this gateway accepts',
                'default' => '',
                'layout' => 'sidebar',
            ],
            'xendit_logo' => [
                'type' => 'media',
                'label' => 'Gateway Logo',
                'hint' => 'Logo displayed at checkout',
                'default' => null,
                'accept' => 'image',
                'layout' => 'sidebar',
            ],
            'xendit_min_amount' => [
                'type' => 'number',
                'label' => 'Minimum Amount',
                'hint' => 'Minimum payment amount (0 = no limit)',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'xendit_max_amount' => [
                'type' => 'number',
                'label' => 'Maximum Amount',
                'hint' => 'Maximum payment amount (0 = no limit)',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'xendit_fixed_charge' => [
                'type' => 'number',
                'label' => 'Fixed Charge',
                'hint' => 'Fixed fee added to each payment',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'xendit_percent_charge' => [
                'type' => 'number',
                'label' => 'Percent Charge',
                'hint' => 'Percentage fee added to each payment',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0|max:100',
                'layout' => 'sidebar',
            ],
        ],
    ],

    'nowpayments' => [
        'label' => 'NOWPayments',
        'layout' => 'full',
        'icon' => 'ph ph-currency-btc',
        'description' => 'NOWPayments cryptocurrency gateway credentials',
        'webhook_url' => true,
        'settings' => [
            'nowpayments_enabled' => [
                'type' => 'feature',
                'label' => 'Enable NOWPayments',
                'hint' => 'Accept cryptocurrency payments via NOWPayments',
                'default' => false,
            ],
            'nowpayments_api_key' => [
                'type' => 'password',
                'label' => 'API Key',
                'hint' => 'Your NOWPayments API key',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'nowpayments_ipn_secret' => [
                'type' => 'password',
                'label' => 'IPN Secret Key',
                'hint' => 'Secret used to verify IPN webhook signatures (HMAC-SHA512)',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'nowpayments_supported_currencies' => [
                'type' => 'tags',
                'label' => 'Supported Currencies',
                'hint' => 'Fiat currencies to price payments in (e.g. USD, EUR)',
                'default' => '',
                'layout' => 'sidebar',
            ],
            'nowpayments_logo' => [
                'type' => 'media',
                'label' => 'Gateway Logo',
                'hint' => 'Logo displayed at checkout',
                'default' => null,
                'accept' => 'image',
                'layout' => 'sidebar',
            ],
            'nowpayments_min_amount' => [
                'type' => 'number',
                'label' => 'Minimum Amount',
                'hint' => 'Minimum payment amount (0 = no limit)',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'nowpayments_max_amount' => [
                'type' => 'number',
                'label' => 'Maximum Amount',
                'hint' => 'Maximum payment amount (0 = no limit)',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'nowpayments_fixed_charge' => [
                'type' => 'number',
                'label' => 'Fixed Charge',
                'hint' => 'Fixed fee added to each payment',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'nowpayments_percent_charge' => [
                'type' => 'number',
                'label' => 'Percent Charge',
                'hint' => 'Percentage fee added to each payment',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0|max:100',
                'layout' => 'sidebar',
            ],
        ],
    ],

    'coinbasecommerce' => [
        'label' => 'Coinbase Commerce',
        'layout' => 'full',
        'icon' => 'ph ph-coins',
        'description' => 'Coinbase Commerce cryptocurrency gateway credentials',
        'webhook_url' => true,
        'settings' => [
            'coinbasecommerce_enabled' => [
                'type' => 'feature',
                'label' => 'Enable Coinbase Commerce',
                'hint' => 'Accept cryptocurrency payments via Coinbase Commerce',
                'default' => false,
            ],
            'coinbasecommerce_api_key' => [
                'type' => 'password',
                'label' => 'API Key',
                'hint' => 'Your Coinbase Commerce API key',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'coinbasecommerce_webhook_secret' => [
                'type' => 'password',
                'label' => 'Webhook Shared Secret',
                'hint' => 'Secret used to verify the X-CC-Webhook-Signature (HMAC-SHA256)',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'coinbasecommerce_supported_currencies' => [
                'type' => 'tags',
                'label' => 'Supported Currencies',
                'hint' => 'Fiat currencies to price payments in (e.g. USD, EUR)',
                'default' => '',
                'layout' => 'sidebar',
            ],
            'coinbasecommerce_logo' => [
                'type' => 'media',
                'label' => 'Gateway Logo',
                'hint' => 'Logo displayed at checkout',
                'default' => null,
                'accept' => 'image',
                'layout' => 'sidebar',
            ],
            'coinbasecommerce_min_amount' => [
                'type' => 'number',
                'label' => 'Minimum Amount',
                'hint' => 'Minimum payment amount (0 = no limit)',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'coinbasecommerce_max_amount' => [
                'type' => 'number',
                'label' => 'Maximum Amount',
                'hint' => 'Maximum payment amount (0 = no limit)',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'coinbasecommerce_fixed_charge' => [
                'type' => 'number',
                'label' => 'Fixed Charge',
                'hint' => 'Fixed fee added to each payment',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'coinbasecommerce_percent_charge' => [
                'type' => 'number',
                'label' => 'Percent Charge',
                'hint' => 'Percentage fee added to each payment',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0|max:100',
                'layout' => 'sidebar',
            ],
        ],
    ],

    'bitpay' => [
        'label' => 'BitPay',
        'layout' => 'full',
        'icon' => 'ph ph-lightning',
        'description' => 'BitPay cryptocurrency gateway credentials',
        'webhook_url' => true,
        'settings' => [
            'bitpay_enabled' => [
                'type' => 'feature',
                'label' => 'Enable BitPay',
                'hint' => 'Accept cryptocurrency payments via BitPay',
                'default' => false,
            ],
            'bitpay_api_token' => [
                'type' => 'password',
                'label' => 'API Token',
                'hint' => 'Your BitPay merchant-facing API token',
                'default' => '',
                'rules' => 'nullable|string|max:255',
            ],
            'bitpay_sandbox' => [
                'type' => 'feature',
                'label' => 'Sandbox Mode',
                'hint' => 'Use the BitPay test environment',
                'default' => true,
            ],
            'bitpay_supported_currencies' => [
                'type' => 'tags',
                'label' => 'Supported Currencies',
                'hint' => 'Fiat currencies to price payments in (e.g. USD, EUR)',
                'default' => '',
                'layout' => 'sidebar',
            ],
            'bitpay_logo' => [
                'type' => 'media',
                'label' => 'Gateway Logo',
                'hint' => 'Logo displayed at checkout',
                'default' => null,
                'accept' => 'image',
                'layout' => 'sidebar',
            ],
            'bitpay_min_amount' => [
                'type' => 'number',
                'label' => 'Minimum Amount',
                'hint' => 'Minimum payment amount (0 = no limit)',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'bitpay_max_amount' => [
                'type' => 'number',
                'label' => 'Maximum Amount',
                'hint' => 'Maximum payment amount (0 = no limit)',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'bitpay_fixed_charge' => [
                'type' => 'number',
                'label' => 'Fixed Charge',
                'hint' => 'Fixed fee added to each payment',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0',
                'layout' => 'sidebar',
            ],
            'bitpay_percent_charge' => [
                'type' => 'number',
                'label' => 'Percent Charge',
                'hint' => 'Percentage fee added to each payment',
                'default' => '0',
                'rules' => 'nullable|numeric|min:0|max:100',
                'layout' => 'sidebar',
            ],
        ],
    ],

];
